---
kind: Service
apiVersion: v1
metadata:
  name: linkerd
spec:
  selector:
    app: linkerd
  type: LoadBalancer
  ports:
  - name: incoming
    port: 4140
    targetPort: 4140
  - name: admin
    port: 9990
    targetPort: 9990
