---
kind: ReplicationController
apiVersion: v1
metadata:
  name: linkerd
spec:
  replicas: 1
  selector:
    app: linkerd
  template:
    metadata:
      labels:
        app: linkerd
    spec:
      containers:
      - name: l5d
        image: buoyantio/linkerd:0.6.0
        args:
        - "/io.buoyant/linkerd/config/config.yml"
        ports:
        - name: incoming
          containerPort: 4140
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "linkerd-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true
        # We run a kubectl proxy container so that linkerd can talk to the
        # Kubernetes master API.
      - name: kubectl
        image: buoyantio/kubectl:1.2.3
        args:
        - proxy
        - "-p"
        - "8001"
      volumes:
      - name: linkerd-config
        configMap:
          name: linkerd-config
