
version: 2
jobs:
  build:
    docker:
      - image: buoyantio/linkerd:1.0.0-rc4
        parallelism: 1 # TODO: parallelize tests
    working_directory: ~/linkerd-examples

    steps:
      - restore_cache:
          key: linkerd-examples-packages

      - run:
          name: Install git
          command: |
            set -ex
            if [ ! -f /usr/bin/curl || ! -f /usr/bin/git ]; then
              apk update
              apk add curl
              apk add git
            fi

      - save_cache:
          key: linkerd-examples-packages
          paths:
            - /usr/bin/curl
            - /usr/bin/git

      # Check out linkerd-examples source code into ~/linkerd-examples.
      - checkout

      - run:
          name: Run examples
          command: |
            ~/linkerd-examples/.circleci/ci.sh
