global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
- job_name: 'linkerd'
  metrics_path: /admin/metrics/prometheus
  static_configs:
  - targets:
    - '127.0.0.1:9990'

- job_name: 'linkerd_tcp'
  static_configs:
  - targets:
    - '127.0.0.1:9992'

- job_name: 'redis1'
  static_configs:
  - targets:
    - '127.0.0.1:9121'

- job_name: 'redis2'
  static_configs:
  - targets:
    - '127.0.0.1:9122'
