global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'linkerd'
  metrics_path: /admin/metrics/prometheus
  static_configs:
  - targets:
    - '127.0.0.1:9990'
  relabel_configs:
  - source_labels: [__address__]
    action: replace
    target_label: instance
    regex: (.+)(?::\d+)
    replacement: $1
  metric_relabel_configs:
  - source_labels: [dst_id]
    action:        replace
    target_label:  service
    regex:         .*/([^/]+)
    replacement:   $1

- job_name: 'linkerd_tcp'
  static_configs:
  - targets:
    - '127.0.0.1:9992'

- job_name: 'redis1'
  static_configs:
  - targets:
    - '127.0.0.1:9121'

- job_name: 'redis2'
  static_configs:
  - targets:
    - '127.0.0.1:9122'
