---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api
spec:
  replicas: 3
  selector:
    app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/helloworld:test7
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - "/bin/bash"
        - "-c"
        - "python api.py"
        ports:
        - name: service
          containerPort: 7779
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  clusterIP: None
  ports:
  - name: http
    port: 7779
