---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/helloworld:test7
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - "/bin/bash"
        - "-c"
        - "HTTP_PROXY=`./hostIP.sh`:4140 python hello.py"
        ports:
        - name: service
          containerPort: 7777
      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - proxy
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  type: ClusterIP
  ports:
  - name: http
    port: 7777
  - name: external
    port: 80
    targetPort: 7777
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: world
spec:
  replicas: 3
  selector:
    app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/helloworld:test7
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - "/bin/bash"
        - "-c"
        - "python world.py"
        ports:
        - name: service
          containerPort: 7778
---
apiVersion: v1
kind: Service
metadata:
  name: world-v1
spec:
  selector:
    app: world
  clusterIP: None
  ports:
  - name: http
    port: 7778
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api
spec:
  replicas: 3
  selector:
    app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/helloworld:test7
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - "/bin/bash"
        - "-c"
        - "python api.py"
        ports:
        - name: service
          containerPort: 7779
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  clusterIP: None
  ports:
  - name: http
    port: 7779
