---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    worker_processes 1;
    events { worker_connections 1024; }

    http {
      sendfile on;

      server {
        listen 80;

        # a test endpoint that returns http 200s
        location / {
          proxy_pass http://httpstat.us/200;
          proxy_set_header  X-Real-IP  $remote_addr;
        }
      }

      server {
        listen 80;
        server_name api.hello.world;

        location / {
          proxy_pass http://l5d.default.svc.cluster.local;
          proxy_set_header Host $host;
          proxy_set_header Connection "";
          proxy_pass_request_headers off;
          proxy_http_version 1.1;
        }
      }

      server {
        listen 80;
        server_name www.hello.world;

        location / {
          proxy_pass http://l5d.default.svc.cluster.local;
          proxy_set_header Host $host;
          proxy_set_header Connection "";
          proxy_pass_request_headers off;
          proxy_http_version 1.1;
        }
      }
    }
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:1.11.5
        ports:
        - containerPort: 80
        volumeMounts:
        - name: "nginx-config"
          mountPath: "/etc/nginx"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
