apiVersion: v1
kind: ReplicationController
metadata:
  name: world
spec:
  replicas: 3
  selector:
    app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: <helloworld docker image>
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NS
          value: helloworld
        command:
        - "/bin/bash"
        - "-c"
        - "HTTP_PROXY=`./hostIP.sh`:4140 python world.py"
        ports:
        - name: service
          containerPort: 7778
